#! /usr/bin/env python3

"""Build mapping.py for osgb from the Perl version

Toby Thurston -- 23 Oct 2017 
"""
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=str, help="file name of your local copy of Maps.pm")
    args = parser.parse_args()
    
    with open(args.source, 'rt') as perl, open('mapping.py', 'wt') as maps:
        print('''
# coding: utf-8
"""Data for OSGB and other walkers maps in England, Wales, Scotland, and Isle of Man.

Toby Thurston -- 23 Oct 2017
"""
from __future__ import unicode_literals
 
map_locker = {''', file=maps)
        for line in perl:
            if not line.startswith('$maps'):
                continue

            line = line[6:].replace('} =',' :',1)
            line = line.replace('=>', ':')
            line = line.replace(';', ',', 1)
            line = line.replace('bbox',     "'bbox'", 1)
            line = line.replace('area',     "'area'", 1)
            line = line.replace('series',   "'series'", 1)
            line = line.replace('number',   "'number'", 1)
            line = line.replace('parent',   "'parent'", 1)
            line = line.replace('title',    "'title'", 1)
            line = line.replace('polygon',  "'polygon'", 1)
            print(line, file=maps, end='')


        print('}', file=maps)


