#! /usr/bin/env python3

"""Build mapping data file for osgb from polygon files

Toby Thurston -- 15 Mar 2016 
"""
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=str, help="file name of your local copy of Maps.pm")
    args = parser.parse_args()
    
    with open(args.source, 'rt') as perl, open('mapping.data', 'wt') as maps:
        print('{', file=maps)
        for line in perl:
            if not line.startswith('$maps'):
                continue

            line = line[6:].replace('} =',' :',1)
            line = line.replace('=>', ':')
            line = line.replace(';', ',', 1)
            line = line.replace('bbox',     "'bbox'", 1)
            line = line.replace('area',     "'area'", 1)
            line = line.replace('series',   "'series'", 1)
            line = line.replace('number',   "'number'", 1)
            line = line.replace('parent',   "'parent'", 1)
            line = line.replace('title',    "'title'", 1)
            line = line.replace('polygon',  "'polygon'", 1)
            print(line, file=maps, end='')


        print('}', file=maps)


